name: rust-build
on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build node
        run: cargo build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build_${{ github.sha }}
          path: target/debug/rust-linux-cross-mac